#!/bin/bash

TAG=$1
IMAGE=$2
USERNAME=$3

echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin 
curl -s http://iam-filesystem.admin/fs/$USERNAME/images/$IMAGE | docker build --rm --no-cache -t $TAG -
docker push $TAG

kubectl apply -f http://iam-filesystem.admin/fs/$USERNAME/kubernetes/$IMAGE --namespace=$USERNAME